version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cto-coach-postgres
    environment:
      POSTGRES_DB: cto_coach
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
